<!doctype html>
<html lang="en">
    <head>
    	<meta charset="utf-8">
    	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">        
        <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    	<script>$(document).ajaxError(function(event, jqXHR, ajaxSettings, thrownError){alert(thrownError)});</script>
    	<title>Cloud-Based Social Robotics</title>
    </head>
    
    <body>
    	<div class="container">        
    		<div class="row">
    			<div class="col-4">
        			<?php echo $this->fetch('settings.phtml'); ?>
        		</div>
    			<div class="col-6 pl-5">
        			<?php echo $this->fetch('services.phtml'); ?>
        		</div>
        	</div>
        	<div class="row mt-5">
        		<div class="col-4">
        			<h5>Local</h5>
        			<ul>
        				<li><a href="https://bitbucket.org/socialroboticshub/output/src/master/computer_browser/" target="_blank">Computer Browser</a></li>
        				<li><a href="https://bitbucket.org/socialroboticshub/input/src/master/computer_camera/" target="_blank">Computer Camera</a></li>
        				<li><a href="https://bitbucket.org/socialroboticshub/input/src/master/computer_microphone/" target="_blank">Computer Microphone</a></li>
        				<li><a href="https://bitbucket.org/socialroboticshub/output/src/master/computer_speakers/" target="_blank">Computer Speakers</a></li>
        			</ul>
        		</div>        		
        	</div>
        </div>
        
        <div class="modal fade" id="popup" tabindex="-1" role="dialog" aria-hidden="true">
          <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body" id="popupContent">
              </div>
            </div>
          </div>
        </div>
    </body>
</html>
